---
        #for Virtual Host
        
- hosts: Virtual host
  tasks:
       - name: add services
	     yum: {{item}}},state=latest
		 with_items:
		           - @^virtualiztion hosts
				   - vsftpd
				   - httpd
				   - tftp-server
				   - nfs-utils
				   - cifs-utils
				   - policycoreutils-python
				   - elinks
				   
				   #TODO
	   - name: create kickstart shared directory
	    file: path=/var/www/html/vm_kickstart state=directory
		
	   - name: copy kickstart files to Virtual Host
		local_action: command rsync -a /root/vm_kickstart/*.cfg /var/www/html/vm_kickstart/
	   
	   - name: start httpd service
	    service: name=http state=restarted
	   
	   - name: enable http service at boot time
	    service: name= http enable=yes
	    
	   - name: setup local  nfs service
	   - name: setup local ftp service
	   - name: setup local dhcp,tftp service
	   
	   - name: install ipa server virtual machine
	   command: 'virt-install --name=ipa
	                         --disk path=/var/lib/libvirt/images/ipa.dsk,size=15
	                         --nographics
					         --vcpus=2
					         --memory=4096
					         --location=http://centos.mirrors.atwab.net/7/os/x86_64
					         --os-type linux
					         --os-variant centos7.0
					         --extra-args="ks=http://localhost/vm_kickstart/ipa.ks.cfg console=ttyS0,115200n8"'
       - name: install services virtual machine
	   command: 'virt-install --name=services
	                         --disk path=/var/lib/libvirt/images/ipa.dsk,size=15
	                         --nographics
					         --vcpus=2
					         --memory=4096
					         --location=http://centos.mirrors.atwab.net/7/os/x86_64
					         --os-type linux
					         --os-variant centos7.0
					         --extra-args="ks=http://localhost/vm_kickstart/services.ks.cfg console=ttyS0,115200n8"'
							 
	   - name: install client1 virtual machine
	   command: 'virt-install --name=client1
	                         --disk path=/var/lib/libvirt/images/ipa.dsk,size=15
	                         --nographics
					         --vcpus=1
					         --memory=2048
					         --location=http://centos.mirrors.atwab.net/7/os/x86_64
					         --os-type linux
					         --os-variant centos7.0
					         --extra-args="ks=http://localhost/vm_kickstart/client1.ks.cfg console=ttyS0,115200n8"'
	   - name: install client2 virtual machine
	   command: 'virt-install --name=client2
	                         --disk path=/var/lib/libvirt/images/ipa.dsk,size=15
	                         --nographics
					         --vcpus=1
					         --memory=2048
					         --location=http://centos.mirrors.atwab.net/7/os/x86_64
					         --os-type linux
					         --os-variant centos7.0
					         --extra-args="ks=http://localhost/vm_kickstart/client2.ks.cfg console=ttyS0,115200n8"'
        - name: Wait for ipa virtual machine rebooting
        wait_for: host="{{ inventory_hostname }}" search_regex=OpenSSH port=22 timeout=300
		
-----------------------------------------------------------------------------------------------------------------------
- host: ipa.sfzhang.com
gather_facts: yes
tasks: 

		
		- name: configure /etc/hosts
        shell:  echo {{ansible_eno16777736.ipv4.address}} {{ansible_nodename}} >>/etc/hosts
		
		- name: configure DNS TO 8.8.8.8
        nmcli: conn_name=eth0 dns4="8.8.8.8" state=present
        
		- name: disable selinux
		selinux: policy=targeted state=permissive
        
		- name: install ipa-server unattended
		shell: ipa-server-install --setup-dns --realm=SFZHANG.COM --domain=sfzhang.com\ 
		                   --ds-password=password --admin-password=password\  
						   --unattended --mkhomedir --forwarder=8.8.8.8\ 
						   --autoreverse
		
		- name: add host entry and otp for client1.sfzhang.com
		shell: ipa host-add client1.sfzhang.com --password=sfzhang
		
		
		- name: add host entry and otp for client2.sfzhang.com
        shell: ipa host-add client2.sfzhang.com --password=sfzhang
		
		
		- name: add host entry and otp for services.sfzhang.com
        shell: ipa host-add services.sfzhang.com --password=sfzhang
        
        - name: enable relevant ipa-server ports in firewall-cmd
        firewalld: service={{item}} state=enabled permanent=true immediate=true
        with_items: 
                   - http
                   - https
                   - ldap
                   - ldaps
                   - kerberos
                   - kpasswd
                   - dns
                   - ntp
        - name: set ipa_server_address to be used by clients
        set_fact: ipa_server_address={{ansible_eno16777736.ipv4.address}}
		
		
-host: client.sfzhang.com
gather_facts: no
tasks: 					
	   - name: ignore peer dns and enable IPA dns on clients
       shell: nmcli c modify eth0 ipv4.ignore-auto-dns=yes ipv4.dns={{ipa_server_address}}
		
	   - name: Generate SSH keys to ensure that ipa-client-install uploads them to the ipa server
       command: /usr/sbin/sshd-keygen
       
       - name: Get the hostname to set as the host principal
       command: /bin/hostname >/tmp/hostname.txt
	   
	   - name: ipa client install
       #Red Hat recommends not to start the sshd service prior to the kickstart enrollment.
       #While starting sshd before enrolling the client generates the SSH keys automatically
       #using the above script is the preferred solution.
       command: "/usr/sbin/ipa-client-install --domain=SFZHANG.COM
                --enable-dns-updates --mkhomedir -w sfzhang 
                --realm=SFZHANG.COM --server=ipa.sfzhang.com 
                --unattended --force-ntpd"
	   
	   #add the server's IP address as the first entry in the list of name servers in the client's /etc/resolv.conf file
#don't do it manually, do it through network manager

# Generate SSH keys to ensure that ipa-client-install uploads them to the IdM server
#/usr/sbin/sshd-keygen

# Get the hostname to set as the host principal
#bin/hostname > /tmp/hostname.txt

### Run the client install script

#/usr/sbin/ipa-client-install --domain=SFZHANG.COM --enable-dns-updates --mkhomedir -w sfzhang --realm=SFZHANG.COM --server=ipa.sfzhang.com --unattended --force-ntpd