---
# created by sfzhang 2016.10.15
# main playbook for executing roles
- hosts: test2.sfzhang.com
  remote_user: sfzhang
  gather_facts: true
  become: true
  become_ask_pass: sfzhang
  roles:
         - sfzhang.myenv
           myenv_user: sfzhang

         - sfzhang.myapache
           enable_apache: true

         - sfzhang.advanced_http

         - sfzhang.mariadb
...

