---
# install and enable web and db service

- name: install apache package
  yum: name={{ansible_local.custom.packages.web_package}} state=latest

- name: install mariadb package
  yum: name={{ansible_local.custom.packages.db_package}} state=latest

- name: setup content of homepage
  copy: content={{http_content}} dest={{web_root}}/index.html

- name: start and enable apache service
  service: name=httpd state=started enabled=true

- name: start and enable mariadb service
  service: name=httpd state=started enabled=true
...
